### ISSUE TITLE
クラス名について

### ISSUE THREAD

**Issue by dolfalf** [LLCCLL/DesignPattern#1]
https://github.com/LLCCLL/DesignPattern/blob/0691d06b2a6c1e458cec2ece0a02d783da3d3cff/dePa/src/singleton/practice/Meteor.java#L3

クラス名だけで用途がわかるようにした方が良いと思います。
`MeteorMedal`はどうですか。

Nomarlクラスも同じようにクラス名の変更をお願いします。

**Comment by LLCCLL** [comment]
解決しました。
