### ISSUE TITLE
Singletonインスタンス生成結果出力

### ISSUE THREAD

**Issue by dolfalf** [LLCCLL/DesignPattern#3]
https://github.com/LLCCLL/DesignPattern/blob/0691d06b2a6c1e458cec2ece0a02d783da3d3cff/dePa/src/singleton/practice/Main.java#L15

singletonでインスタンスをいくつか生成して比較する処理を入れてください。
普通のインスタンスの生成と違う結果になることを出力した方が良いです。

**Comment by LLCCLL** [comment]
改善しました。
